apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    aline.service: bank
  name: bank
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.service: bank
  template:
    metadata:
      labels:
        aline.service: bank
    spec:
      containers:
      - name: bank
        image: lyndasm/aline-bank-microservice
        ports:
          - containerPort: 8083
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    aline.service: bank
  name: bank
spec:
  ports:
    - name: bank-port
      port: 8083
      targetPort: 8083
  selector:
    aline.service: bank
