apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  namespace: aline
  labels:
    aline.component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.component: server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        aline.component: server
    spec:
      containers:
      - name: bank
        image: lyndasm/aline-account-microservice
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8072
        env:
        - name: APP_PORT
          value: "8072"
        - name: DB_USERNAME
          value: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: DB_PASSWORD
        - name: DB_HOST
          value: mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: alinedb
        - name: ENCRYPT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: encrypt-key
              key:  ENCRYPT_SECRET_KEY
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-key
              key:  JWT_SECRET_KEY
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
      restartPolicy: Always
