apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
  namespace: aline
  labels:
    aline.component: transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.component: transaction
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        aline.component: transaction
    spec:
      containers:
      - name: transaction
        image: lyndasm/aline-transaction-microservice
        ports:
          - containerPort: 8073
        env:
        - name: DB_USERNAME
          value: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: DB_PASSWORD
        - name: DB_HOST
          value: mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: alinedb
        - name: APP_SERVICE_HOST
          value: host.docker.internal
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
      restartPolicy: Always
