apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aline-client-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: aline
spec:
  # tls:
  # - hosts:
  #   - alinefinancial.com
  #   secretName: aline-tls-secret
  rules:
    - host: alinefinancial.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing-service
                port:
                  number: 4200
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: admin-service
                port:
                  number: 3000
          - path: /landing
            pathType: Prefix
            backend:
              service:
                name: landing-service
                port:
                  number: 4200
          - path: /member
            pathType: Prefix
            backend:
              service:
                name: member-service
                port:
                  number: 3007
