apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    aline.service: landing
  name: landing
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.service: landing
  template:
    metadata:
      labels:
        aline.service: landing
    spec:
      containers:
      - name: landing
        image: lyndasm/aline-landing
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    aline.service: landing
  name: landing
spec:
  ports:
    - name: landing
      port: 4200
      targetPort: 80
  selector:
    aline.service: landing