apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aline-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: aline
  labels:
    aline.component: aline-client-ingress
spec:
  # tls:
  # - hosts:
  #   - alinefinancial.com
  #   secretName: aline-tls-secret
  rules:
    - host: alinefinancial.com
      http:
        paths:
        - pathType: Prefix
          path: "/api"
          backend:
            service:
              name: server-cluster
              port: 
                number: 8080
    - host: alinefinancial.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing-service
                port:
                  number: 4200
    - host: admin.alinefinancial.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-service
                port:
                  number: 3000
    - host: landing.alinefinancial.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing-service
                port:
                  number: 4200
    - host: member.alinefinancial.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: member-service
                port:
                  number: 3007
