apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    aline.service: transaction
  name: transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.service: transaction
  template:
    metadata:
      labels:
        aline.service: transaction
    spec:
      containers:
      - name: transaction
        image: lyndasm/aline-transaction-microservice
        ports:
          - containerPort: 8073
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    aline.service: transaction
  name: transaction
spec:
  ports:
    - name: transaction-port
      port: 8073
      targetPort: 8073
  selector:
    aline.service: transaction