apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    aline.service: underwriter
  name: underwriter
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.service: underwriter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        aline.service: underwriter
    spec:
      containers:
      - name: underwriter
        image: lyndasm/aline-underwriter-microservice
        ports:
          - containerPort: 8071
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    aline.service: underwriter
  name: underwriter
spec:
  ports:
    - name: underwriter-port
      port: 8071
      targetPort: 8071
  selector:
    aline.service: underwriter
