version: "3.8"

x-aws-vpc: "vpc-0897dd7e0c1fa2efb"
x-aws-loadbalancer: aline-network-lb

x-variables: &variables
  DB_USERNAME: admin
  DB_PASSWORD: ${DB_PASSWORD}
  DB_HOST: mysql
  DB_PORT: 3306
  DB_NAME: alinedb
  ENCRYPT_SECRET_KEY: ${ENCRYPT_SECRET_KEY}
  JWT_SECRET_KEY: ${JWT_SECRET_KEY}
  APP_SERVICE_HOST: ${LB}

x-react-variables: &react-variables
  REACT_APP_MEMBER_DASHBOARD_URL: http://lf-aline-member.s3-website-us-west-1.amazonaws.com
  REACT_APP_API_BASEURL: ${LB}
  REACT_APP_API: ${LB}/api/

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: admin
      MYSQL_DATABASE: alinedb
    ports:
      - 3306:3306
    restart: always

  gateway:
    image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/lf-aline-gateway
    ports:
      - 80:80
    environment:
      APP_PORT: 80
      PORTAL_LANDING: http://lf-aline-landing.s3-website-us-west-1.amazonaws.com
      PORTAL_DASHBOARD: http://lf-aline-member.s3-website-us-west-1.amazonaws.com
      PORTAL_ADMIN: http://lf-aline-admin.s3-website-us-west-1.amazonaws.com
      APP_SERVICE_HOST: ${LB}
    restart: on-failure

  user:
    image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/lf-aline-user-microservice
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.7'
          memory: '1Gi'
        reservations:
          cpus: '0.5'
          memory: 512Mi
    ports:
      - 8071:8071
    environment:
      <<: *variables
      APP_PORT: 8071
    restart: on-failure

    # http://alinefinancial-ecs.com:8071/swagger-ui/index.html
    # "username": "samantha_carter",
    # "password": "LtColone1!",
    # "role": "admin",
    # "firstName": "Samantha",
    # "lastName": "Carter",
    # "email": "samantha.carter@sg1.com",
    # "phone": "555-555-5555"

  account:
    image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/lf-aline-account-microservice
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1Gi'
        reservations:
          cpus: '0.5'
          memory: 512Mi
    ports:
      - 8072:8072
    environment:
      <<: *variables
      APP_PORT: 8072
    restart: on-failure

  bank:
    image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/lf-aline-bank-microservice
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1Gi'
        reservations:
          cpus: '0.5'
          memory: 512Mi
    ports:
      - 8083:8083
    environment:
      <<: *variables
      APP_PORT: 8083
    restart: on-failure

  card:
    image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/lf-aline-card-microservice
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1Gi'
        reservations:
          cpus: '0.5'
          memory: 512Mi
    ports:
      - 8084:8084
    environment:
      <<: *variables
      APP_PORT: 8084
    restart: on-failure

  transaction:
    image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/lf-aline-transaction-microservice
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1Gi'
        reservations:
          cpus: '0.5'
          memory: 512Mi
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8073:8073
    environment:
      <<: *variables
      APP_PORT: 8073
    restart: on-failure

  underwriter:
    image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/lf-aline-underwriter-microservice
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1Gi'
        reservations:
          cpus: '0.5'
          memory: 512Mi
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8070:8070
    environment:
      <<: *variables
      APP_PORT: 8070
    restart: on-failure

x-aws-cloudformation:
  Resources:
    GatewayTCP80TargetGroup:
      Properties:
        HealthCheckIntervalSeconds: 180
        HealthCheckTimeoutSeconds: 30
        HealthyThresholdCount: 5
        UnhealthyThresholdCount: 5
    UserTCP8071TargetGroup:
      Properties:
        HealthCheckIntervalSeconds: 180
        HealthCheckTimeoutSeconds: 30
        HealthyThresholdCount: 5
        UnhealthyThresholdCount: 5
    AccountTCP8072TargetGroup:
      Properties:
        HealthCheckIntervalSeconds: 180
        HealthCheckTimeoutSeconds: 30
        HealthyThresholdCount: 5
        UnhealthyThresholdCount: 5
    BankTCP8083TargetGroup:
      Properties:
        HealthCheckIntervalSeconds: 180
        HealthCheckTimeoutSeconds: 30
        HealthyThresholdCount: 5
        UnhealthyThresholdCount: 5
    CardTCP8084TargetGroup:
      Properties:
        HealthCheckIntervalSeconds: 180
        HealthCheckTimeoutSeconds: 30
        HealthyThresholdCount: 5
        UnhealthyThresholdCount: 5
    TransactionTCP8073TargetGroup:
      Properties:
        HealthCheckIntervalSeconds: 180
        HealthCheckTimeoutSeconds: 30
        HealthyThresholdCount: 5
        UnhealthyThresholdCount: 5
    UnderwriterTCP8070TargetGroup:
      Properties:
        HealthCheckIntervalSeconds: 180
        HealthCheckTimeoutSeconds: 30
        HealthyThresholdCount: 5
        UnhealthyThresholdCount: 5