apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  namespace: aline
  labels:
    aline.component: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.component: admin
  template:
    metadata:
      labels:
        aline.component: admin
    spec:
      imagePullSecrets:
        - name: aws-registry-key
      containers:
      - name: admin
        image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/aline-admin-portal
        ports:
          - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
      restartPolicy: Always

