apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-deployment
  namespace: aline
  labels:
    aline.component: member
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.component: member
  template:
    metadata:
      labels:
        aline.component: member
    spec:
      containers:
      - name: member
        image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/aline-member-dashboard
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
      restartPolicy: Always
