apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwriter-deployment
  namespace: aline
  labels:
    aline.component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.component: server
  template:
    metadata:
      labels:
        aline.component: server
    spec:
      imagePullSecrets:
        - name: aws-registry-key
      containers:
      - name: underwriter
        image: 052911266688.dkr.ecr.us-west-1.amazonaws.com/aline-underwriter-microservice
        ports:
          - containerPort: 8071
        env:
        - name: APP_PORT
          value: "8071"
        envFrom:
        - secretRef:
            name: aline-config
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
      restartPolicy: Always