apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-deployment
  namespace: aline
spec:
  replicas: 1
  selector:
    matchLabels:
      aline.component: client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        aline.component: client
    spec:
      containers:
      - name: landing
        image: lyndasm/aline-landing
        ports:
          - containerPort: 4200
        env:
          - name: REACT_APP_API_BASEURL
            value: http://localhost:8080
          - name: REACT_APP_API
            value: http://localhost:8080/api
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
      restartPolicy: Always
